---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tidyverse)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# run_analysis
    
```{r function-run_analysis}
#' Run the analysis
#' @param df a data frame
#' @param folder_in_which_to_save_csv_files character. folder in which to save the csv files
#' @return a message
#'
#' @export
run_analysis <- function(df, folder_in_which_to_save_csv_files) {
  if (!is.data.frame(df)) {
    stop("df must be a data frame")
  }

  if (!dir.exists(folder_in_which_to_save_csv_files)) {
    stop("folder_in_which_to_save_csv_files must be a valid directory")
  }

  nrow_df <- get_df_nrows(df)

  filtered_data <- filter_squirrels_data_based_on_integrity(df)

  if (nrow(filtered_data$df_valid_data) > 0) {
    save_as_csv(
      df = filtered_data$df_valid_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "valid_data.csv")
    )
  }

  if (nrow(filtered_data$df_invalid_data) > 0) {
    save_as_csv(
      df = filtered_data$df_invalid_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "invalid_data.csv")
    )
  }

  if (nrow(filtered_data$df_missing_data) > 0) {
    save_as_csv(
      df = filtered_data$df_missing_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "missing_data.csv")
    )
  }

  message("all csv files saved in ", folder_in_which_to_save_csv_files)

  return(folder_in_which_to_save_csv_files)
}
```
  
```{r example-run_analysis}
data("data_demo_squirrels")
output_dir <- tempfile()
dir.create(output_dir)
run_analysis(df = data_demo_squirrels, folder_in_which_to_save_csv_files = output_dir)
unlink(output_dir, recursive = TRUE)
```
    
```{r tests-run_analysis}
test_that("run_analysis works with client data", {
  output_dir <- tempfile()
  dir.create(output_dir)

  data <- readxl::read_excel(
    system.file("nyc_squirrels_client_file_to_be_used_as_reference.xlsx", package = "squirrels")
  )
  run_analysis(data, output_dir)

  expect_true(file.exists(file.path(output_dir, "valid_data.csv")))
  expect_true(file.exists(file.path(output_dir, "invalid_data.csv")))
  expect_true(file.exists(file.path(output_dir, "missing_data.csv")))

  valid_data <- read.csv2(file.path(output_dir, "valid_data.csv"))

  expect_equal(
    nrow(valid_data),
    362
  )

  invalid_data <- read.csv2(file.path(output_dir, "invalid_data.csv"))
  expect_equal(
    nrow(invalid_data),
    6
  )

  missing_data <- read.csv2(file.path(output_dir, "missing_data.csv"))
  expect_equal(
    nrow(missing_data),
    4
  )
  unlink(output_dir, recursive = TRUE)
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_run_analysis.Rmd",
  vignette_name = "Run analysis",
  overwrite = TRUE,
  open_vignette = FALSE
)
```

