# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_plus_in_primary_fur_color works", {
  
  expect_true(inherits(check_plus_in_primary_fur_color, "function")) 
  
  
  vect_ok <- c("Black", "Black+Cinnamon", "Cinnamon", NA)
  expect_equal(object = check_plus_in_primary_fur_color(primary_fur_color = vect_ok), 
               expected = c(TRUE, FALSE, TRUE, NA)
  )
  
  expect_equal(object = check_plus_in_primary_fur_color(primary_fur_color = c("Black", "Cinnamon", "Cinnamon", NA)), 
               expected = c(TRUE, TRUE, TRUE, NA)
  )
  
  expect_error(object = check_plus_in_primary_fur_color(primary_fur_color = 9999), 
                 regexp = "primary_fur_color is not a character")
  
})
