# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_presence_of_required_columns works", {
  expect_true(inherits(check_presence_of_required_columns, "function")) 
  
  
  expect_true(
    check_presence_of_required_columns(data = data_demo_squirrels)
    )
  
  expect_error(check_presence_of_required_columns(data = iris), 
               regexp = "Columns are missing")
})
