# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand


mon_dossier_temp <- tempfile(pattern = "saveascsv")
dir.create(mon_dossier_temp)
mypath <- file.path(mon_dossier_temp, "output.csv")
  

test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function")) 
  
  path <- iris |> save_as_csv(mypath)

  expect_true(
    file.exists(path)
  )

})

test_that("save_as_csv return Error", {
  
# erreur : l'extension du fichier à créer n'est pas la bonne
expect_error(
  iris |> save_as_csv(file.path(mon_dossier_temp, "output.xlsx")),
  "mypath must be a csv")

# erreur : la fonction n'est pas appliquée à un data.frame
expect_error(
  NULL |> save_as_csv(file.path(mon_dossier_temp, "output.csv")),
  "df is not a data frame")

# erreur : le chemin où doit être enregistré le fichier n'existe pas
expect_error(
  iris |> save_as_csv(file.path(mon_dossier_temp, "nexiste/pas/output.csv")),
  "mypath does not exist")
  
# jeu de données vide
  expect_error(
    data.frame() |> save_as_csv(file.path(mon_dossier_temp, "output.csv")),
    "df has an empty dataframe"
  )

})
