# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("filter_squirrels_data_based_on_integrity works", {
  expect_true(inherits(filter_squirrels_data_based_on_integrity, "function"))
 
  my_data <- readr::read_csv(system.file("nyc_squirrels_sample.csv", package = "squirrels"))
  
  
  data_integrity <- filter_squirrels_data_based_on_integrity(data = my_data)
  
  expect_equal(
    nrow(data_integrity$df_valid_data),
    393
  )
  
  expect_equal(
    nrow(data_integrity$df_invalid_data),
    0
  )
  
  expect_equal(
    nrow(data_integrity$df_missing_data),
    7
  )
})
