# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

test_that("save_as_csv works", {
  expect_true(inherits(save_as_csv, "function")) 
  
  
mon_dossier_temp <- tempfile(pattern = "saveascsv")
dir.create(mon_dossier_temp)
mypath <- file.path(mon_dossier_temp, "output.csv")
  
})

