# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

test_that("check_coordinates works", {
  expect_true(inherits(check_coordinates, "function")) 
  
  
both_valid_latitude <- c(40.766, 40.799)
both_valid_longitude <- c(-73.96, -73.95)
both_invalid_latitude <- c(30, 32)
both_invalid_longitude <- c(-100, -99)
one_invalid_latitude <- c(40.766, 50)
one_invalid_longitude <- c(-73.95, -100)

  
expect_equal(object = check_coordinates(
  latitude = both_valid_latitude,
  longitude = both_valid_longitude
), expected = c(TRUE, TRUE))


expect_equal(object = check_coordinates(
  latitude = both_invalid_latitude,
  longitude = both_invalid_longitude
), expected = c(FALSE, FALSE))


expect_equal(object = check_coordinates(
  latitude = one_invalid_latitude,
  longitude = one_invalid_longitude
), expected = c(TRUE, FALSE))

  
})


test_that("check_coordinates works with an error", {
  
  expect_error(object =  check_coordinates(
            latitude = "coucou",
            longitude = "ca va"
              ), regexp = "latitude and longitude should be numeric")
  
})

test_that("check_presence_of_required_columns works", {
  expect_true(inherits(check_presence_of_required_columns, "function")) 
})

test_that("j'ai un message d'erreur quand il le faut", {
  expect_error(check_presence_of_required_columns(data_not_ok), "Missing column : primary_fur_color, lat, long")
})

test_that("j'ai les bonnes colonnes", {
  expect_true(check_presence_of_required_columns(data_demo_squirrels))
})
