# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Checks if the coordinates are in Central Park
#'
#' @param latitude numeric. A vector with the latitude.
#' @param longitude numeric. A vector with the longitude.
#' @return a vector of logicals
#'
#' @export
#' @examples
#' both_valid_latitude <- c(40.766, 40.799)
#' both_valid_longitude <- c(-73.96, -73.95)
#' both_invalid_latitude <- c(30, 32)
#' both_invalid_longitude <- c(-100, -99)
#' one_invalid_latitude <- c(40.766, 50)
#' one_invalid_longitude <- c(-73.95, -100)
#'
#' check_coordinates(
#'   latitude = both_valid_latitude,
#'   longitude = both_valid_longitude
#' )
#'
#' check_coordinates(
#'   latitude = both_invalid_latitude,
#'   longitude = both_invalid_longitude
#' )
#'
#' check_coordinates(
#'   latitude = one_invalid_latitude,
#'   longitude = one_invalid_longitude
#' )
check_coordinates <- function(latitude, longitude) {
  if (isFALSE(is.numeric(latitude)) | isFALSE(is.numeric(longitude))) {
    stop("latitude and longitude should be numeric")
  }

  coordinates_are_ok <-
    latitude > 40.76400 & latitude < 40.80100 &
      longitude > -73.98300 & longitude < -73.94735

  return(coordinates_are_ok)
}

#' check the presence of required columns
#' 
#' Vérifie que le jeu de données continet bien les colonnes requises pour l'étude des écureuils de Central Park
#' 
#' @return
#' 
#' @export
#' @examples
#' data_is_ok <- data_demo_squirrels
#' check_presence_of_required_columns(data_is_ok)
#' data_not_ok <- iris
#' check_presence_of_required_columns(data_not_ok)
check_presence_of_required_columns <- function(dataframe){
   data <- dataframe 
   expected_names <- c("primary_fur_color", "lat","long")
   check_names <- all(expected_names %in% names(data))
  
  if (isFALSE(check_names)){
  stop("Missing column : primary_fur_color, lat, long")}
   
    return(check_names)
}


