# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Verify if the required columns are present in the dataset
#'
#' long, lat and primary_fur_color are required
#'
#' @param data Data frame. A dataset with squirrels data.
#'
#' @return logical
#' 
#' @export
#' @examples
#' check_presence_of_required_columns(data = data_demo_squirrels)
check_presence_of_required_columns <- function(data){
    
  required_columns <-
    all(c("primary_fur_color", "lat", "long") %in% names(data))
  
  if (isFALSE(required_columns)) {
    stop("Columns are missing")
  }
  
  return(required_columns)
  
  
}
