# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' check the presence of required columns
#' 
#' Vérifie que le jeu de données continet bien les colonnes requises pour l'étude des écureuils de Central Park
#'
#' @param dataframe tableau de données
#' @return logical
#' @export
#' @examples
#' data <- data_demo_squirrels
#' check_presence_of_required_columns(data)
#'

check_presence_of_required_columns <- function(dataframe){

   expected_names <- c("primary_fur_color", "lat","long")
   check_names <- all(expected_names %in% names(dataframe))
  
  if (isFALSE(check_names)){
  stop("Missing column : primary_fur_color, lat, long")}
   
    return(check_names)
}


