# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand

#' Filter the data based on the quality of the primary fur color and the coordinates
#'
#' 
#' @param data Data frame. A dataset with squirrels data.
#' @importFrom dplyr mutate case_when filter
#'
#' @return a list with valid, invalid, missing data
#' 
#' @export
#' @examples
#' filter_squirrels_data_based_on_integrity(data = data_demo_squirrels)
#'
#'
#' my_data <- readr::read_csv(system.file("nyc_squirrels_sample.csv", package = "squirrels"))
#' filter_squirrels_data_based_on_integrity(data = my_data)
#'
filter_squirrels_data_based_on_integrity <- function(data){
    
  
  check_columns <- check_presence_of_required_columns(data = data)
  
  colors_are_ok <-
    check_plus_in_primary_fur_color(primary_fur_color = data$primary_fur_color)
  
  coordinates_are_ok <-
    check_coordinates(latitude = data$lat, longitude = data$long)
  
  
  data_with_type <- data |>
    mutate(
      type = case_when(
        is.na(colors_are_ok) | is.na(coordinates_are_ok) ~ "missing",
        colors_are_ok & coordinates_are_ok ~ "valid",
        !colors_are_ok | !coordinates_are_ok ~ "invalid"
      )
    )
  
  valid_data <- data_with_type |>
    filter(type == "valid")
  invalid_data <- data_with_type |>
    filter(type == "invalid")
  missing_data <- data_with_type |>
    filter(type == "missing")
  
  
  list(
    df_valid_data = valid_data,
    df_invalid_data = invalid_data,
    df_missing_data = missing_data
  )
  
  
}
