# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand

#' To get a message with the number of rows in a data frame of interest with `get_df_nrows()`.
#' 
#' @param data dataframe The dataset to be used
#' 
#' @importFrom glue glue
#' 
#' @return numeric (the number of rows)  and a message 
#' @export
#' @examples
#' get_df_nrows(data = iris)
get_df_nrows <- function(data){
  
  if (isFALSE(inherits(data, "data.frame"))) {
    stop("data must be a data.frame")
  }
  
  
  nrow_data <- nrow(data)
  
  message(glue("The dataset is composed of {nrow_data} rows"))

  return(nrow_data)
}
