# WARNING - Generated by {fusen} from dev/flat_run_analysis.Rmd: do not edit by hand

#' Run the analysis
#' @param df a data frame
#' @param folder_in_which_to_save_csv_files character. folder in which to save the csv files
#' @return a message
#'
#' @export
#' @examples
#' data("data_demo_squirrels")
#' output_dir <- tempfile()
#' dir.create(output_dir)
#' run_analysis(df = data_demo_squirrels, folder_in_which_to_save_csv_files = output_dir)
#' unlink(output_dir, recursive = TRUE)
run_analysis <- function(df, folder_in_which_to_save_csv_files) {
  if (!is.data.frame(df)) {
    stop("df must be a data frame")
  }

  if (!dir.exists(folder_in_which_to_save_csv_files)) {
    stop("folder_in_which_to_save_csv_files must be a valid directory")
  }

  nrow_df <- get_df_nrows(df)

  filtered_data <- filter_squirrels_data_based_on_integrity(df)

  if (nrow(filtered_data$df_valid_data) > 0) {
    save_as_csv(
      df = filtered_data$df_valid_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "valid_data.csv")
    )
  }

  if (nrow(filtered_data$df_invalid_data) > 0) {
    save_as_csv(
      df = filtered_data$df_invalid_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "invalid_data.csv")
    )
  }

  if (nrow(filtered_data$df_missing_data) > 0) {
    save_as_csv(
      df = filtered_data$df_missing_data,
      mypath = file.path(folder_in_which_to_save_csv_files, "missing_data.csv")
    )
  }

  message("all csv files saved in ", folder_in_which_to_save_csv_files)

  return(folder_in_which_to_save_csv_files)
}
