# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' export  file
#'
#' save as CSV
#' @param df 
#' @param mypath le chemin où enregistrer mon df
#' @param ... 
#' @importFrom utils write.csv2
#' @importFrom tools file_ext
#' @return le chemin d'enregistrement
#' @export
#'
#' @examples
#'
#' path <- "mondossier"
#'
#' mon_dossier_temp <- tempfile(pattern = "saveascsv")
#' dir.create(mon_dossier_temp)
#' mypath <- file.path(mon_dossier_temp, "output.csv")
#'
#' save_as_csv(df = iris, mypath = mypath)
#' unlink(mypath)
save_as_csv <- function(df, mypath, ...) {
  # Créer un dossier temporaire pour le fichier CSV
  mon_dossier_temp <- tempfile(pattern = "saveascsv")
  dir.create(mon_dossier_temp)
  mypath <- file.path(mon_dossier_temp, "output.csv")

  # Vérifier si df est un data frame
  if (!is.data.frame(df)) {
    stop("df is not a data frame")
  }

  # Vérifier si df est vide
  if (nrow(df) == 0) {
    stop("df is an empty dataframe")
  }

  # Vérifier si mypath est un fichier CSV
  if (file_ext(mypath) != "csv") {
    stop("mypath must be a csv")
  }

  # Vérifier si le dossier de mypath existe
  if (!dir.exists(dirname(mypath))) {
    stop("my path does not exist")
  }
  write.csv2(x = df, file = mypath, ...)

  message("Finish: writing")
  return(mypath)
}

