# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' Save an output as a csv file
#'
#' @param df Data frame. The table to be saved as a csv file.
#' @param mypath Character. Path where the csv file should be saved.
#' @param ... parameters of 'write.csv2()'
#' @importFrom tools file_ext
#' @importFrom utils write.csv2
#'
#' @return The path to the created csv file.
#' @export
#'
#' @examples

#'
#' path <- "mondossier"
#'
#' mon_dossier_temp <- tempfile(pattern = "saveascsv")
#' dir.create(mon_dossier_temp)
#' mypath <- file.path(mon_dossier_temp, "output.csv")
#'
#' save_as_csv(df = iris, mypath = mypath)
#' unlink(mypath)
save_as_csv <- function(df, mypath,...){
    
  
if (isFALSE(is.data.frame(df))) {
  stop("df is not a data frame")
}

if (isTRUE(nrow(df) == 0)) {
  stop("df has an empty dataframe")
}

if (isFALSE(file_ext(mypath) == "csv" )){
  stop("mypath must be a csv")
}

if (isFALSE(dir.exists(dirname(mypath)))){
  stop("mypath does not exist")
}

write.csv2(x = df, file = mypath,...)
message("Finish : Writing")
return(mypath)
  
}

