# WARNING - Generated by {fusen} from dev/flat_export_results.Rmd: do not edit by hand

#' export_results Title
#'
#' @param df dataframe
#' @param path le chemin où enregistrer mon df
#'
#' @return le chemin d'enregistrement
#' @export
#' @importFrom utils write.csv2
#' @importFrom tools file_ext
#' @examples

#' export_results()
save_as_csv <- function(df, mypath ) {
mon_dossier_temp <- tempfile(pattern = "saveascsv")
dir.create(mon_dossier_temp)
mypath <- file.path(mon_dossier_temp, "output.csv")

if(isFALSE(is.data.frame(df))){
  stop("df is not a data frame")
}
if(isTRUE(nrow(df) == 0 )){
  stop("df is an empty dataframe")
}
if(isFALSE(file_ext(mypath) == "csv" )){
  stop("mypath must be a csv")
}

if(isFALSE(dir.exists(dirname(mypath)))){
  stop("my path does not exists")
}

 write.csv2(x=df, file=mypath) 
 message("Finish: writing") 
 return(mypath)
}
